id = "pyncz.tokyo-night-dark"
name = "Tokyo Night Dark theme"
description = "A contrast modification of the Tokyo Night theme"
version = "0.1.0"
schema_version = 1
authors = ["pyncz <https://github.com/pyncz>"]
repository = "https://github.com/pyncz/zed-tokyo-night-dark-theme"
themes = ["themes/tokyo-night-dark.json"]
